@startuml
'https://plantuml.com/activity-diagram-beta

start
:tryAcquireShared(int);
:获得当前state;
if (独占锁持有数不为0) then (true)
  if(独占锁持有线不是当前线程) then (true)
  if (isForward?) then (no)
    :Process controls;
    if (continue processing?) then (no)
      stop
    endif

    if (isPost?) then (yes)
      :Page.onPost();
    else (no)
      :Page.onGet();
    endif
    :Page.onRender();
  endif
else (false)
endif

if (do redirect?) then (yes)
  :redirect process;
else
  if (do forward?) then (yes)
    :Forward request;
  else (no)
    :Render page template;
  endif
endif

stop

@enduml
