dubbo:
  application:
    name: provider
    register-mode: instance
  protocol:
    name: tri
    port: -1
  registry:
    id: zk-registry
    address: zookeeper://172.18.64.119:2181
  config-center:
    address: zookeeper://172.18.64.119:2181
  metadata-report:
    address: zookeeper://172.18.64.119:2181
server:
  port: 8082